# Cloud Foundry Java Buildpack
# Copyright 2013-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for the Tomcat container
---
tomcat:
  version: 9.+
  repository_root: "{default.repository.root}/tomcat"
  context_path: 
  external_configuration_enabled: false
external_configuration:
  version: 1.+
  repository_root: 
lifecycle_support:
  version: 3.+
  repository_root: "{default.repository.root}/tomcat-lifecycle-support"
logging_support:
  version: 3.+
  repository_root: "{default.repository.root}/tomcat-logging-support"
access_logging_support:
  version: 3.+
  repository_root: "{default.repository.root}/tomcat-access-logging-support"
  access_logging: disabled
redisson:
  version: 3.+
  repository_root: "{default.repository.root}/redisson"
  database: 0
  timeout: 3000
  connect_timeout: 10000
  connection_pool_size: 64
  session_update_mode: DEFAULT
geode_store:
  # The version of Geode Store must be less than or equal to your Tanzu Gemfire for VMs version to ensure compatibility.
  # The Geode Store version is pinned to 1.12.4 to be compatible with the most commonly used versions of Tanzu Gemfire for VMs.
  version: 1.12.5
  repository_root: https://java-buildpack-tomcat-gemfire-store.s3-us-west-2.amazonaws.com
